<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Theme\Block\Html\Header\CriticalCss $criticalCssViewModel
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$staticUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_STATIC); // to get Base Url without index.php

?>
<?php $criticalCssViewModel = $block->getData('criticalCssViewModel'); ?>

<?php
if (true) {
?>
<script no-move="react-luma">
if ( window.innerWidth < 768) {
    const st = `<?= $criticalCssViewModel->getCriticalCssData() ?>`;
    const style = document.createElement('style');
    style.innerHTML = st;
    document.head.appendChild(style);
} else {
    var cssonload = () =>{ setTimeout(()=>{document.getElementsByTagName('body')[0].style.display = 'block'; console.log("CSS loaded")}, 50);};
    const st = "<link rel=\"stylesheet\" media=\"all\" href=\"<?= $staticUrl ?>styles-m.css\"><link rel=\"stylesheet\" media=\"screen and (min-width: 768px)\" onload=\"cssonload()\" href=\"<?= $staticUrl ?>frontend/Magento/luma/en_US/css/styles-l.css\">";
    document.head.insertAdjacentHTML( 'beforeend', st);
    const body = "<style> body{display:none} </style>";
    document.head.insertAdjacentHTML( 'beforeend', body);
}
</script>
<?php
}
?>

<style type="text/css">
<?php //echo $criticalCssViewModel->getCriticalCssData() ?>

@media only screen and (max-width: 768px) {
    .catalog-product-view .product.media {
        -ms-flex-order: -1;
        -webkit-order: -1;
        order: -1; 
    }
.catalog-product-view .product.media {
        -ms-flex-order: -1;
        -webkit-order: -1;
        order: -1;
    }
    .catalog-product-view .product-media {
        min-height: 380px;
    }
    .header.content {
        min-height: 79px;
    }
    .page-header {
        border-bottom: none !important;
        margin-bottom: 0px !important;
    }
}
</style>