<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menuHtml = $block->getHtml('level-top', 'submenu', $columnsLimit)
?>
<style>
.sections.nav-sections {
    display: none;
    z-index: 999;
    position: absolute;
    top: 80px;
    left: 0;
}
</style>

<script>

document.querySelector("#maincontent").addEventListener('click', (e) => {
        const nav = document.querySelector('.sections.nav-sections');
        if(nav.style.display == "block"){
                nav.style.display = "none";
        }}
);

document.querySelectorAll('.level0.category-item').forEach(
    e => {
        console.log(e); 
        e.addEventListener('mouseenter', e => { m = e.target.querySelector('.submenu');
        document.querySelectorAll('.submenu').forEach((e)=>{console.log(e);
            e.addEventListener('mouseleave', e => { e.target.style.display='none'; return false});
            e.style.display='none'});
        if (m !== null) m.style.display = "block"; });
    }
    );

document.querySelector('.action.nav-toggle').addEventListener('click', e => {

const nav = document.querySelector('.sections.nav-sections');

console.log(nav.style.position);

if (nav.style.display === "none" || nav.style.display === "") {
        nav.style.display = "block";
} else {
        nav.style.display = "none";
}

return false;
})

</script>

<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?= /* @noEscape */ $_menuHtml?>
        <?= $block->getChildHtml() ?>
    </ul>
</nav>
