<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>

<?php
$images = $block->getGalleryImages()->getItems();
$mainImage = current(array_filter($images, function ($img) use ($block) {
    return $block->isMainImage($img);
}));

if (!empty($images) && empty($mainImage)) {
    $mainImage = $block->getGalleryImages()->getFirstItem();
}

$helper = $block->getData('imageHelper');
$mainImageData = $mainImage ?
    $mainImage->getData('medium_image_url') :
    $helper->getDefaultPlaceholderUrl('image');

?>

<div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">

<!--
<div id="picture-resize">
    <img width="100%" height="100%" alt="main product photo"  class="gallery-placeholder__image image_full" srcset="<?= /* @noEscape */ \Mage::imageResizeUrl($mainImageData, 350, 350, 'p', 75, 'media/') ?> 480w, <?= /* @noEscape */ \Mage::imageResizeUrl($mainImageData, 650, 650, 'p', 75, 'media/') ?> 800w"  sizes="(max-width: 600px) 480px,800px"  src="<?= /* @noEscape */ \Mage::imageResizeUrl($mainImageData, 650, 650, 'p', 75, 'media/') ?>"> 
</div>
-->

<picture>   
    <source srcset="<?= /* @noEscape */ \Mage::imageResizeUrl($mainImageData, 700, 700, 'p', 95, 'media/') ?>" media="(min-width: 768px)">
    <source srcset="<?= /* @noEscape */ \Mage::imageResizeUrl($mainImageData, 350, 350, 'p', 95, 'media/') ?>" media="(min-width: 414px)">
    <img width="100%" height="100%" class="gallery-placeholder__image image_full"  alt="main product photo"  src="<?= /* @noEscape */ \Mage::imageResizeUrl($mainImageData, 350, 350, 'p', 75, 'media/') ?>" > 
</picture> 

</div>
<?php if (false) { 
    ?>
<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?= /* @noEscape */ $block->getMagnifier() ?>,
                "data": <?= /* @noEscape */ $block->getGalleryImagesJson() ?>,
                "options": <?= /* @noEscape */ $block->getGalleryOptions()->getOptionsJson() ?>,
                "fullscreen": <?= /* @noEscape */ $block->getGalleryOptions()->getFSOptionsJson() ?>,
                 "breakpoints": <?= /* @noEscape */ $block->getBreakpoints() ?>
            }
        }
    }
</script>

<?php
}
?>
